controller_manager:
  ros__parameters:
    update_rate: 200 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    PD_control:
      type: rbt_pd_cnt/Rbt_PD_cnt
      
PD_control:
  ros__parameters:
    joint:
      - Joint_1
    K_d:
      - 10.0 # Nm/rad
    K_p: 
      - 80.0
    init_pos:
      - 0.0
    use_sim_time: True

joint_state_broadcaster:
  ros__parameters:
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
      - Joint_7
      - Joint_8
      - Joint_9
      - Joint_10
      - Joint_11
      - Joint_12
      - Joint_13
      - Joint_14
      - Joint_15
      - Joint_16
      - Joint_17
      - Joint_18
      - Joint_19
      - Joint_20
      - Joint_21

    use_sim_time: True
    
    # interfaces:
    #   - position
    #   - velocity
    #   - effort
